Fix python 3 map error in multilang
In Python 3, map returns an iterable object which is not serializable. This breaks when we try to encode it on line 78:

TypeError: <map object at 0x7fb659dfef98> is not JSON serializable